"""add missing tables

Revision ID: acf845ceed0f
Revises: a4a055acb0de
Create Date: 2026-04-17 11:41:22.335925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf845ceed0f'
down_revision: Union[str, Sequence[str], None] = 'a4a055acb0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_logs_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('cost_per_input_token', sa.Float(), nullable=True),
    sa.Column('cost_per_output_token', sa.Float(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_llm_provider_configs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_provider_configs'))
    )
    op.create_table('style_libraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('NEWS', 'ART', 'ENTERTAINMENT', 'CINEMA', 'MARKETING', 'PERSONAL', name='library_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('quality_tier', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_single_voice', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_style_libraries_owner_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_style_libraries_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_libraries'))
    )
    op.create_table('presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('rewrite_mode', sa.Enum('CONSERVATIVE', 'BALANCED', 'EXPRESSIVE', name='rewrite_mode'), nullable=False),
    sa.Column('semantic_contract_mode', sa.Enum('STRICT', 'BALANCED', 'LOOSE', name='semantic_contract_mode'), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('intervention_level', sa.Float(), nullable=False),
    sa.Column('active_heuristics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['style_libraries.id'], name=op.f('fk_presets_library_id_style_libraries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presets'))
    )
    op.create_table('rewrite_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('rewrite_mode', sa.Enum('CONSERVATIVE', 'BALANCED', 'EXPRESSIVE', name='rewrite_mode'), nullable=False),
    sa.Column('semantic_contract_mode', sa.Enum('STRICT', 'BALANCED', 'LOOSE', name='semantic_contract_mode'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ANALYZING', 'REWRITING', 'EVALUATING', 'COMPLETED', 'FAILED', name='rewrite_task_status'), nullable=False),
    sa.Column('input_constraints', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['style_libraries.id'], name=op.f('fk_rewrite_tasks_library_id_style_libraries')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_rewrite_tasks_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rewrite_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewrite_tasks'))
    )
    op.create_table('style_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('formality', sa.Float(), nullable=True),
    sa.Column('sentence_length_mean', sa.Float(), nullable=True),
    sa.Column('sentence_length_variance', sa.Float(), nullable=True),
    sa.Column('burstiness_index', sa.Float(), nullable=True),
    sa.Column('target_perplexity_min', sa.Float(), nullable=True),
    sa.Column('target_perplexity_max', sa.Float(), nullable=True),
    sa.Column('rhythm_profile', sa.JSON(), nullable=True),
    sa.Column('lexical_signature', sa.JSON(), nullable=True),
    sa.Column('syntax_patterns', sa.JSON(), nullable=True),
    sa.Column('composition_profile', sa.JSON(), nullable=True),
    sa.Column('linguistic_markers', sa.JSON(), nullable=True),
    sa.Column('guidance_signals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['style_libraries.id'], name=op.f('fk_style_profiles_library_id_style_libraries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_profiles'))
    )
    op.create_table('style_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('quality_tier', sa.Enum('L1', 'L2', 'L3', name='quality_tier'), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['style_libraries.id'], name=op.f('fk_style_samples_library_id_style_libraries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_samples'))
    )
    op.create_table('rewrite_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('CONSERVATIVE', 'BALANCED', 'EXPRESSIVE', name='rewrite_mode_variant'), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('intermediate_scores', sa.JSON(), nullable=True),
    sa.Column('style_match_score', sa.Float(), nullable=True),
    sa.Column('semantic_preservation_score', sa.Float(), nullable=True),
    sa.Column('perplexity_score', sa.Float(), nullable=True),
    sa.Column('burstiness_score', sa.Float(), nullable=True),
    sa.Column('fluency_win_rate', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['rewrite_tasks.id'], name=op.f('fk_rewrite_variants_task_id_rewrite_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rewrite_variants'))
    )
    op.create_table('evaluation_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('absolute_metrics', sa.JSON(), nullable=True),
    sa.Column('judge_scores', sa.JSON(), nullable=True),
    sa.Column('pairwise_scores', sa.JSON(), nullable=True),
    sa.Column('contract_violations', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['rewrite_tasks.id'], name=op.f('fk_evaluation_reports_task_id_rewrite_tasks')),
    sa.ForeignKeyConstraint(['variant_id'], ['rewrite_variants.id'], name=op.f('fk_evaluation_reports_variant_id_rewrite_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_reports')
    op.drop_table('rewrite_variants')
    op.drop_table('style_samples')
    op.drop_table('style_profiles')
    op.drop_table('rewrite_tasks')
    op.drop_table('presets')
    op.drop_table('style_libraries')
    op.drop_table('llm_provider_configs')
    op.drop_table('audit_logs')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
