global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # configure alertmanager host here

scrape_configs:
  - job_name: humanizator_api
    static_configs:
      - targets: ["app:8000"]
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
